### ISSUE TITLE
The OOB prediction in the rust rf function

### ISSUE THREAD

**Issue by qianchd** [mlondschien/changeforest#139]
In R, the prediction method with "prob" argument of randomForest package returns the rate of votes of the base trees. I am not that fimilar to Rust. I try to read the source code of the random forest code in biosphere. It seems the same as R did?

See the following question in stackexchange.
[random-forest-probability](https://stats.stackexchange.com/questions/364298/random-forest-probability)
The Method 1 is what the R did. Is the rf function in Rust works as the Method 2？

**Comment by qianchd** [comment]
> Yes, the random forests used in changeforest predict probabilities according to _method 2_.

Thanks for your reply! It is a spired work! I try the probability estimation including the two methods today. The function in R-package `randomForest` uses method 1 and `ranger` uses method 2. Here is the sample code.

```
library(ranger)
library(tictoc)
library(ggplot2)
library(tidyr)
library(dplyr)
library(randomForest)
simulate_data <- function(n){
  X <- data.frame(matrix(runif(n*10), ncol = 10))
  Y <- data.frame(Y = rbinom(n, size = 1, prob = apply(X^3*2, 1, sum) %>%
                               pnorm(mean = 5)
  ) %>% as.factor())
  dplyr::bind_cols(X, Y)
}

train_data <- simulate_data(5000)
test_data <- simulate_data(5000)

tic("ranger")
model_ranger <- ranger(Y ~., data = train_data,
                        num.trees = 100,
                        mtry = floor(sqrt(10)),
                        write.forest = T,
                        min.node.size = 100,
                        probability = T
)
toc()

tic("randomForest")
model_randomForest <- randomForest(Y ~., data = train_data,
                                    ntree = 100,
                                    mtry = floor(sqrt(10)),
                                    nodesize = 100
)
toc()

pred_ranger <- predict(model_ranger, test_data)$predictions[,2]

# rfUtilities::probability.calibration(Y, pred_ranger, regularization = TRUE)

pred_rf <- predict(model_randomForest, test_data, type = "prob")[,2]
Y = as.numeric(test_data$Y) - 1
pred_rf_calibrated <- rfUtilities::probability.calibration(Y, pred_rf)


prob_real <- apply(test_data[,1:10]^3*2, 1, sum) %>% pnorm(mean = 5)

print(c(mean((pred_rf - prob_real)^2), 
        mean((pred_ranger - prob_real)^2),
        mean((pred_rf_calibrated - prob_real)^2)))

data.frame(prob_real, pred_ranger, pred_rf, pred_rf_calibrated) %>%
  tidyr::gather(method, prob, -prob_real) %>%
  ggplot(aes(x = prob, y = prob_real)) + geom_point(size = 0.1) + facet_wrap(~method)
```
Also I try the probability calibration algorithm Isotonic Regression, it seems that in this setting, all the probabilities estimator could be biased. But overall, it is enough to detect the signals once changes occur.

![Rplot](https://user-images.githubusercontent.com/48825214/226526104-a94d1d46-4869-43c6-a020-dc4cedc41a9a.png)

**Comment by mlondschien** [comment]
You can use the _method 2_ aggregation with any random forest library for 2-class classification by treating the classification problem as a regression problem of $Y \in \\{0.0, 1.0\\}$. It is true that random forests (or most classifiers) will struggle to produce calibrated probability estimates. However, there is evidence suggesting that method 2 produces better calibrated estimates, which is why they are used in changeforest.

**Comment by qianchd** [comment]
> You can use the _method 2_ aggregation with any random forest library for 2-class classification by treating the classification problem as a regression problem of Y∈{0.0,1.0}. It is true that random forests (or most classifiers) will struggle to produce calibrated probability estimates. However, there is evidence suggesting that method 2 produces better calibrated estimates, which is why they are used in changeforest.

Quite agree. A approximated class probability estimation (with nearly monotone property) shall be enough for CP detection.
