### ISSUE TITLE
Specify area in which no segmentation is allowed

### ISSUE THREAD

**Issue by enzbus** [mlondschien/changeforest#150]
Hello,

I wonder if it would be difficult to implement this extra feature. Basically I would like to tell changeforest that it can't place a segmentation between two indexes that I specify (which could also be from or to one of the two extremes). I can also look into the code and submit a PR if it sounds like a feature you'd like to add. If I understand correctly only [this function](https://github.com/mlondschien/changeforest/blob/103897768be51f9965b879a3de6310f154ed7780/src/segmentation.rs#L90) would change, and it would access some new elements of the hyperparameters struct...

Thanks!

**Comment by mlondschien** [comment]
Hi @enzbus. Thanks for your interest in changeforest.

Yes, this should be possible, and it sounds like a welcome addition to changeforest. IIUC, this should be enforceable by adjusting the `optimizer.split_candidates` method:

https://github.com/mlondschien/changeforest/blob/103897768be51f9965b879a3de6310f154ed7780/src/optimizer/optimizer.rs#L20-L28

The `GridSearch` optimizer should work right out of the box. For the `TwoStepSearch`, you would need to adjust these lines as well, to make sure you don't filter out all initial guesses:

https://github.com/mlondschien/changeforest/blob/103897768be51f9965b879a3de6310f154ed7780/src/optimizer/two_step_search.rs#L61-L64

As you mentioned, you could pass the "forbidden segments" via the `control` hyperparameter.

Please feel free to open a PR and let me know if you have any questions on the implementation.
